const types ={
  APP_INITIALIZE : 'APP_INITIALIZE',
  RECEIVE_MENU: 'RECEIVE_MENU',
  REQUEST_BRAND: 'REQUEST_BRAND',
  RECEIVE_BRAND: 'RECEIVE_BRAND',
  REQUEST_TAGS: 'REQUEST_TAGS',
  RECEIVE_TAGS: 'RECEIVE_TAGS',
  REQUEST_WORK: 'REQUEST_WORK',
  RECEIVE_WORK: 'RECEIVE_WORK',
  REQUEST_SKILLS: 'REQUEST_SKILLS',
  RECEIVE_SKILLS: 'RECEIVE_SKILLS',
  REQUEST_PROJECT: 'REQUEST_PROJECT',
  RECEIVE_PROJECT: 'RECEIVE_PROJECT'
};

export default types